export const products = [
  {
    id: 1,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/04/1-spaghetto-quadrato.jpg",
    title: "N.4 Spaghetto Quadrato Bucato",
    tipo: "lunga",
    cottura: 6,
  },
  {

    id: 2,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/04/5-fettuccine.jpg",
    title: "N.5 Fettuccine",
    tipo: "lunga",
    cottura: 13,
  },
  {
    id: 3,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/04/6-linguine.jpg",
    title: "N.6 Linguine",
    tipo: "lunga",
    cottura: 12,
  },
  {
    id: 4,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/04/7-mezze-linguine.jpg",
    title: "N.7 Mezze Linguine",
    tipo: "lunga",
    cottura: 11,
  },
  {
    id: 5,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/04/11-spaghettino-quadrato.jpg",
    title: "n.11 Spaghettino Quadrato",
    tipo: "lunga",
    cottura: 9,
  },
  {
    id: 6,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/38-mezze-maniche.jpg",
    title: "N.38 Mezze maniche",
    tipo: "corta",
    cottura: 12,
  },
  {
    id: 7,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/44-sedani.jpg",
    title: "N.44 Sedani",
    tipo: "corta",
    cottura: 8,
  },
  {
    id: 8,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/49-sedani.jpg",
    title: "N.49 Sedanini",
    tipo: "corta",
    cottura: 8,
  },
  {
    id: 9,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/53-lumachine.jpg",
    title: "N.53 Lumachine",
    tipo: "corta",
    cottura: 12,
  },
  {
    id: 10,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/55-chifferi-rigati.jpg",
    title: "N.55 Chifferi rigati",
    tipo: "corta",
    cottura: 12,
  },
  {
    id: 11,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/05/58-misto-corto.jpg",
    title: "N.58 Misto corto",
    tipo: "corta",
    cottura: 9,
  },
  {
    id: 12,
    src: "https://www.lamolisana.it/wp-content/uploads/2021/06/84-ditale-quadrato.jpg",
    title: "N.84 Ditale Quadrato",
    tipo: "cortissima",
    cottura: 12,
  },
] 
